### ISSUE TITLE
GuideBook 1.9-1.5 Crash

### ISSUE THREAD

**Issue by YngFox** [Creysys/GuideBook#2]
Here's my crash report. Works when I remove this mod but crashes when placed back in mod folder.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  SleepCore (Sleep-1.9-1.0.0.jar)
  ProgressionTransformer (Progression-1.9-0.5.1.jar)
  FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  LoadingPlugin (HardcoreDarkness-MC1.9-1.8.jar)
  LoadingPluginHardModeTweaks (HardModeTweaks-1.9-1.2.2.jar)
  Player Stats Core (PlayerStats_1.9-1.1.0.jar)
  LoadingPlugin (Bloodmoon-MC1.9-1.4.jar)
  CXLibraryCore (cxlibrary-1.0.0.jar)
  Reborn Core ASM (RebornCore-1.9-2.3.2.84-universal.jar)
  FMLPlugin (InventoryTweaks-1.61-dev-44.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 5/18/16 6:05 PM
Description: addIngredients

java.lang.IllegalArgumentException: Can not set final net.minecraft.item.Item field net.minecraft.potion.PotionHelper$ItemPredicateInstance.field_185195_a to crazypants.enderzoo.potion.Potions$ItemPredicateInstance
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
	at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38)
	at java.lang.reflect.Field.get(Field.java:387)
	at com.creysys.guideBook.plugin.vanilla.recipe.handler.RecipeHandlerBrewing.addIngredients(RecipeHandlerBrewing.java:64)
	at com.creysys.guideBook.plugin.vanilla.recipe.handler.RecipeHandlerBrewing.addVanillaBrewingRecipes(RecipeHandlerBrewing.java:90)
	at com.creysys.guideBook.plugin.vanilla.recipe.handler.RecipeHandlerBrewing.getRecipes(RecipeHandlerBrewing.java:149)
	at com.creysys.guideBook.api.RecipeManager.load(RecipeManager.java:38)
	at com.creysys.guideBook.GuideBookMod.postIinit(GuideBookMod.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:561)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:770)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:316)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5069653896 bytes (4834 MB) / 5839519744 bytes (5569 MB) up to 5839519744 bytes (5569 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144M -Xms6144M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.23 Powered by Forge 12.16.1.1907 Optifine OptiFine_1.9_HD_U_B1 69 mods loaded, 69 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.1.1907.jar) 
	UCHIJ	Forge{12.16.1.1907} [Minecraft Forge] (forge-1.9-12.16.1.1907.jar) 
	UCHIJ	hardmodetweakscore{1.0.0} [Hard Mode Tweaks Core] (minecraft.jar) 
	UCHIJ	playerstatscore{1.1.0} [Player Stats Core] (minecraft.jar) 
	UCHIJ	SleepCore{1.9-1.0.0-CUSTOM} [SleepCore] (minecraft.jar) 
	UCHIJ	JEI{3.4.0.202} [Just Enough Items] (jei_1.9.4-3.4.0.202.jar) 
	UCHIJ	abyssalcraft{1.9.1.6} [AbyssalCraft] (AbyssalCraft-1.9-1.9.1.6.jar) 
	UCHIJ	ArmorDamageRecalc{1.1} [Armor Damage Recalc] (Armor Recalc 1.1.jar) 
	UCHIJ	armorplus{1.7.3} [ArmorPlus] (ArmorPlus-1.7.3(1.9).jar) 
	UCHIJ	bagginses{2.3.0b} [Bagginses] (Bagginses-1.9-2.3.0b.jar) 
	UCHIJ	Baubles{1.2.0.2} [Baubles] (Baubles-1.9-1.2.0.2.jar) 
	UCHIJ	baublesstuff{2.0.9} [Baubles Stuff] (baublesstuff-2.0.9.jar) 
	UCHIJ	BetterAchievements{0.2.5.19} [Better Achievements] (BetterAchievements-1.9-0.2.5.19.jar) 
	UCHIJ	betterquesting{1.2.94} [Better Questing] (BetterQuesting-1.2.94.jar) 
	UCHIJ	BiomesOPlenty{4.0.2.2018} [Biomes O' Plenty] (BiomesOPlenty-1.9-4.0.2.2018-universal.jar) 
	UCHIJ	Bloodmoon{1.2} [Bloodmoon] (Bloodmoon-MC1.9-1.4.jar) 
	UCHIJ	bq_themed{0.0.2 Alpha} [ThemedQuestingPack] (bq_themed-1.2.0.jar) 
	UCHIJ	cavern{1.0.2} [Cavern] (Cavern_1.9-v1.0.2.jar) 
	UCHIJ	ChestTransporter{2.3.0} [Chest Transporter] (ChestTransporter-2.3.0-MC1.9.jar) 
	UCHIJ	craftablehorsearmour{1.0} [Craftable Horse Armour [CHA&S]] (CraftableHorseArmourAndSaddle-1.0.jar) 
	UCHIJ	cxlibrary{1.0.0} [CXLibrary] (cxlibrary-1.0.0.jar) 
	UCHIJ	wonderfulwands{2.0.0} [Wonderful Wands] (CyanosWonderfulWands_1.9.0-2.0.0.jar) 
	UCHIJ	cyclopscore{0.6.0} [Cyclops Core] (CyclopsCore-1.9-0.6.0.jar) 
	UCHIJ	dldungeonsjdg{1.8.11} [Doomlike Dungeons] (DoomlikeDungeons-1.8.11-MC1.9.jar) 
	UCHIJ	double_jump{1.0.0} [DoubleJump] (Double Jump-1.9-1.0.0.jar) 
	UCHIJ	samsprojectiles{1.2.2} [Ender Projectiles] (EnderProjectiles-1.9-1.2.2 (1).jar) 
	UCHIJ	EnderZoo{1.9-1.2.38} [Ender Zoo] (EnderZoo-1.9-1.2.38.jar) 
	UCHIJ	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.9-1.6.jar) 
	UCHIJ	fe{1.2} [Food Expansion] (FoodExpansion1.2-mc1.9.jar) 
	UCHIJ	samsfragiletorches{1.0.1} [Fragile Torches] (FragileTorches-1.9-1.0.1.jar) 
	UCHIJ	grapple_hooks{1.0.8} [Grapple Hooks] (Grapple Hooks-1.9-1.0.8.jar) 
	UCHI	guideBook{1.0} [Guide Book] (GuideBook-1.9-1.5.jar) 
	UCHI	HardcoreDarkness{1.8} [Hardcore Darkness] (HardcoreDarkness-MC1.9-1.8.jar) 
	UCHI	hardmodetweaks{@1.9-1.2.2@} [Hard Mode Tweaks] (HardModeTweaks-1.9-1.2.2.jar) 
	UCHI	hopperducts{1.4.7} [Hopper Ducts] (hopperducts-mc1.9-1.4.7.jar) 
	UCHI	InfernalMobs{1.6.9} [Infernal Mobs] (InfernalMobs-1.9.jar) 
	UCHI	inventorytweaks{1.61-dev-44-8aeffff} [Inventory Tweaks] (InventoryTweaks-1.61-dev-44.jar) 
	UCHI	jet_packs{1.0.0} [Just JetPacks] (JustJetpacks-1.0.0.jar) 
	UCHI	lycanitesmobs{1.14.0.0 - MC 1.9.0} [Lycanites Mobs] (LycanitesMobsComplete 1.14.0.0 BETA06 [1.9.0] (1).jar) 
	UCHI	arcticmobs{1.14.0.0 - MC 1.9.0} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.14.0.0 BETA06 [1.9.0] (1).jar) 
	UCHI	desertmobs{1.14.0.0 - MC 1.9.0} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.14.0.0 BETA06 [1.9.0] (1).jar) 
	UCHI	forestmobs{1.14.0.0 - MC 1.9.0} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.14.0.0 BETA06 [1.9.0] (1).jar) 
	UCHI	freshwatermobs{1.14.0.0 - MC 1.9.0} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.14.0.0 BETA06 [1.9.0] (1).jar) 
	UCHI	infernomobs{1.14.0.0 - MC 1.9.0} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.14.0.0 BETA06 [1.9.0] (1).jar) 
	UCHI	mountainmobs{1.14.0.0 - MC 1.9.0} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.14.0.0 BETA06 [1.9.0] (1).jar) 
	UCHI	plainsmobs{1.14.0.0 - MC 1.9.0} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.14.0.0 BETA06 [1.9.0] (1).jar) 
	UCHI	saltwatermobs{1.14.0.0 - MC 1.9.0} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.14.0.0 BETA06 [1.9.0] (1).jar) 
	UCHI	shadowmobs{1.14.0.0 - MC 1.9.0} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.14.0.0 BETA06 [1.9.0] (1).jar) 
	UCHI	swampmobs{1.14.0.0 - MC 1.9.0} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.14.0.0 BETA06 [1.9.0] (1).jar) 
	UCHI	modifiable_armor{2.0.1} [Modifiable Armor 2] (Modifiable-Armor-1.0.1.jar) 
	UCHI	moreanvils{5.0.0.6} [More Anvils] (MoreAnvils-5.0.0.6.jar) 
	UCHI	moreanvilsvc{3.0} [More Anvils Version Checker] (MoreAnvils-5.0.0.6.jar) 
	UCHI	morefuelsmod-1.9{1.3.2} [§4§lMore Fuels Mod] (morefuelsmod-1.9-v1.3.2.jar) 
	UCHI	MoreFurnaces{1.6.0} [More Furnaces] (MoreFurnaces-1.6.0-MC1.9.jar) 
	UCHI	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.2-5 (1).jar) 
	UCHI	playerstats{1.1.0} [Player Stats] (PlayerStats_1.9-1.1.0.jar) 
	UCHI	progression{0.5.1} [Progression] (Progression-1.9-0.5.1.jar) 
	UCHI	RealisticTorches{1.5.3} [Realistic Torches] (RealisticTorches-1.9-1.5.3.jar) 
	UCHI	reborncore{2.3.2.84} [RebornCore] (RebornCore-1.9-2.3.2.84-universal.jar) 
	UCHI	xreliquary{1.9-1.3.1.342} [Reliquary] (Reliquary-1.9-1.3.1.342.jar) 
	UCHI	AS_Ruins{16.0} [Ruins Spawning System] (Ruins-1.9.jar) 
	UCHI	SimpleGraves{1.9-1.0.0-8} [SimpleGraves] (SimpleGraves-1.9-1.0.0-8.jar) 
	UCHI	Sleep{1.9-1.0.0-CUSTOM} [Sleep] (Sleep-1.9-1.0.0.jar) 
	UCHI	soulshardstow{1.9-2.3.9-25} [Soul Shards - The Old Ways] (SoulShards-TOW-1.9-2.3.9-25.jar) 
	UCHI	bq_standard{1.2.73} [Standard Expansion] (StandardExpansion-1.2.73.jar) 
	UCHI	supercraftingframe{1.1.0.38} [Super Crafting Frame] (supercraftingframe-1.9-1.1.0.38.jar) 
	UCHI	Trashcans{2.0.2} [Trashcans] (Trashcans-1.9-2.0.2.jar) 
	UCHI	AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.9.jar) 
	Loaded coremods (and transformers): 
SleepCore (Sleep-1.9-1.0.0.jar)
  com.arc.sleep.asm.PatchCollection
ProgressionTransformer (Progression-1.9-0.5.1.jar)
  joshie.progression.asm.ProgressionTransformer
FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
LoadingPlugin (HardcoreDarkness-MC1.9-1.8.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
LoadingPluginHardModeTweaks (HardModeTweaks-1.9-1.2.2.jar)
  com.hea3ven.hardmodetweaks.core.ClassTransformerHardModeTweaks
Player Stats Core (PlayerStats_1.9-1.1.0.jar)
  mrdimka.playerstats.core.CoreClassTransformer
LoadingPlugin (Bloodmoon-MC1.9-1.4.jar)
  lumien.bloodmoon.asm.ClassTransformer
CXLibraryCore (cxlibrary-1.0.0.jar)
  cubex2.cxlibrary.CoreModTransformer
Reborn Core ASM (RebornCore-1.9-2.3.2.84-universal.jar)
  reborncore.asm.RebornClassTransformer
FMLPlugin (InventoryTweaks-1.61-dev-44.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 365.19' Renderer: 'GeForce GTX 970M/PCIe/SSE2'
	OptiFine Version: OptiFine_1.9_HD_U_B1
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: SEUS-v10.1-Ultra-Motion-Blur.zip
	OpenGlVersion: 4.5.0 NVIDIA 365.19
	OpenGlRenderer: GeForce GTX 970M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by Creysys** [comment]
Thanks for the report, it will be fixed in the next version.
